version: "4"
services:
  talk:
    image: coralproject/talk:9.11.3
    restart: always
    ports:
      - "172.17.0.1:5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/coral
      - REDIS_URI=redis://redis:6379
      - SIGNING_SECRET=${SIGNING_SECRET}
      - FORCE_SSL=true
      - TRUST_PROXY=true
      - ENABLE_GRAPHIQL=true

  mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:3.2
    restart: always
    volumes:
      - ./data/redis:/data
