FROM coralproject/talk:latest

# Bundle app source
ONBUILD COPY . /usr/src/app

# At this stage, we need to install the development dependancies again because
# we need to have webpack available. We then build the new dependancies and
# clear out the development dependancies again. After this we of course need to
# clear out the yarn cache, this saves quite a lot of size.
ONBUILD RUN cli plugins reconcile && \
            yarn build
