module.exports = {
  USERS_NEW: 'USERS_NEW',
  ACTIONS_DELETE: 'ACTIONS_DELETE',
  ACTIONS_NEW: 'ACTIONS_NEW',
  COMMENTS_NEW: 'COMMENTS_NEW',
  COMMENTS_EDIT: 'COMMENTS_EDIT',
  USERS_SUSPENSION_CHANGE: 'USERS_SUSPENSION_CHANGE',
  USERS_BAN_CHANGE: 'USERS_BAN_CHANGE',
  USERS_USERNAME_STATUS_CHANGE: 'USERS_USERNAME_STATUS_CHANGE',
};
