import React, { StatelessComponent, useCallback, useState } from "react";
import { graphql, RelayPaginationProp } from "react-relay";

import { UserTableContainer_query as QueryData } from "talk-admin/__generated__/UserTableContainer_query.graphql";
import { UserTableContainerPaginationQueryVariables } from "talk-admin/__generated__/UserTableContainerPaginationQuery.graphql";
import { IntersectionProvider } from "talk-framework/lib/intersection";
import { withPaginationContainer } from "talk-framework/lib/relay";

import UserTable from "../components/UserTable";

interface Props {
  query: QueryData | null;
  relay: RelayPaginationProp;
}

const UserTableContainer: StatelessComponent<Props> = props => {
  const users = props.query
    ? props.query.users.edges.map(edge => edge.node)
    : [];
  const [disableLoadMore, setDisableLoadMore] = useState(false);
  const loadMore = useCallback(
    () => {
      if (!props.relay.hasMore() || props.relay.isLoading()) {
        return;
      }
      setDisableLoadMore(true);
      props.relay.loadMore(
        10, // Fetch the next 10 feed items
        error => {
          setDisableLoadMore(false);
          if (error) {
            // tslint:disable-next-line:no-console
            console.error(error);
          }
        }
      );
    },
    [props.relay]
  );

  return (
    <IntersectionProvider>
      <UserTable
        loading={!props.query}
        users={users}
        onLoadMore={loadMore}
        hasMore={props.relay.hasMore()}
        disableLoadMore={disableLoadMore}
      />
    </IntersectionProvider>
  );
};

// TODO: (cvle) This should be autogenerated.
interface FragmentVariables {
  count: number;
  cursor?: string;
}

const enhanced = withPaginationContainer<
  Props,
  UserTableContainerPaginationQueryVariables,
  FragmentVariables
>(
  {
    query: graphql`
      fragment UserTableContainer_query on Query
        @argumentDefinitions(
          count: { type: "Int!", defaultValue: 10 }
          cursor: { type: "Cursor" }
        ) {
        users(first: $count, after: $cursor)
          @connection(key: "UserTable_users") {
          edges {
            node {
              id
              ...UserRowContainer_user
            }
          }
        }
      }
    `,
  },
  {
    direction: "forward",
    getConnectionFromProps(props) {
      return props.query && props.query.users;
    },
    // This is also the default implementation of `getFragmentVariables` if it isn't provided.
    getFragmentVariables(prevVars, totalCount) {
      return {
        ...prevVars,
        count: totalCount,
      };
    },
    getVariables(props, { count, cursor }, fragmentVariables) {
      return {
        count,
        cursor,
      };
    },
    query: graphql`
      # Pagination query to be fetched upon calling 'loadMore'.
      # Notice that we re-use our fragment, and the shape of this query matches our fragment spec.
      query UserTableContainerPaginationQuery($count: Int!, $cursor: Cursor) {
        ...UserTableContainer_query @arguments(count: $count, cursor: $cursor)
      }
    `,
  }
)(UserTableContainer);

export default enhanced;
