export const FETCH_ASSETS = 'FETCH_ASSETS';
export const FETCH_ASSETS_SUCCESS = 'FETCH_ASSETS_SUCCESS';
export const FETCH_ASSETS_FAILED = 'FETCH_ASSETS_FAILED';
export const UPDATE_ASSET = 'UPDATE_ASSET';
