module.exports = {
  SEARCH_ASSETS: 'SEARCH_ASSETS',
  SEARCH_OTHER_USERS: 'SEARCH_OTHER_USERS',
  SEARCH_ACTIONS: 'SEARCH_ACTIONS',
  SEARCH_NON_NULL_OR_ACCEPTED_COMMENTS: 'SEARCH_NON_NULL_OR_ACCEPTED_COMMENTS',
  SEARCH_OTHERS_COMMENTS: 'SEARCH_OTHERS_COMMENTS',
  SEARCH_COMMENT_STATUS_HISTORY: 'SEARCH_COMMENT_STATUS_HISTORY',
  VIEW_USER_STATUS: 'VIEW_USER_STATUS',
  VIEW_PROTECTED_SETTINGS: 'VIEW_PROTECTED_SETTINGS',
  LIST_OWN_TOKENS: 'LIST_OWN_TOKENS',
  VIEW_USER_ROLE: 'VIEW_USER_ROLE',
};
