/**
 * The actual content of this file is being generated by our `locales-loader`.
 * Please check `./src/loaders` and the webpack config for more information.
 *
 * This file only represents the types that gets exported.
 */

import { LocalesData } from "coral-framework/lib/i18n";

export default {} as LocalesData;
