# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Talk Documentation
description: > # this means to ignore newlines until "baseurl:"
  Documentation and guides for Talk from The Coral Project.
baseurl: "/talk" # the subpath of your site, e.g. /blog
url: "https://coralproject.github.io" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-73335347-5
versions:
  node: 8+
  yarn: 1.3.2+
  mongodb: 3.2+
  redis: 3.2.5+
  docker: 17.06.2+
  docker_compose: 1.14.0+

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

plugins:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Collections
collections:
  docs:
    output: true
    permalink: /:path/

# Defaults
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: doc