import { negotiateLanguages as negotiate } from "fluent-langneg/compat";

import { LocalesData } from "./locales";

/**
 * negotiateLanguages accepts `userLocales` which usually comes from
 * `navigator.languages` and the locales `data` as generated by
 * the `locales-loader` and returns an array of matching languages.
 */
export default function negotiateLanguages(
  userLocales: ReadonlyArray<string>,
  data: LocalesData
) {
  // Choose locale that is best for the user.
  const languages = negotiate(userLocales, data.availableLocales, {
    defaultLocale: data.defaultLocale,
    strategy: "lookup",
  });

  if (data.fallbackLocale && languages[0] !== data.fallbackLocale) {
    // Use default locale as fallback in case we have
    // missing keys.
    languages.push(data.fallbackLocale);
  }

  return languages;
}
