#!/bin/sh

# created by `scripts/install-git-hooks.sh` and copied from `scripts/hooks/` into `.git/hooks`.
# To update the git commit hooks, modify this file and then run `sh install-git-hooks.sh` from
# within the `scripts` folder.

FAST_LINT=true

cd server

npx pnpm run precommit

cd ../client

npx pnpm run precommit
